// AUTO-GENERATED by scripts/validate-campus-assets.mjs — do not edit manually
// Run: npm run campus:validate

import type { CampusBuildingVariant } from "./campus-visual-tiers";

export type CampusAssetFileState = {
  webp: boolean;
  png: boolean;
  raster: string | null;
  svg: boolean;
};

export type CampusVariantInventory = {
  idle: Record<"tier1" | "tier2" | "tier3", CampusAssetFileState>;
  construction: Record<
    "stage1" | "stage2" | "stage3" | "stage4" | "stage5",
    CampusAssetFileState
  >;
  aiVerified: boolean;
  aiIdleVerified: boolean;
  aiConstructionVerified: boolean;
  rasterCount: number;
  requiredRaster: number;
  idleRasterCount: number;
  constructionRasterCount: number;
};

export const CAMPUS_ASSET_INVENTORY = {
  "masterBackground": {
    "webp": false,
    "png": true,
    "raster": "png",
    "svg": true
  },
  "animations": {
    "excavator": {
      "webp": false,
      "png": false,
      "raster": null,
      "svg": true
    },
    "dumpTruck": {
      "webp": false,
      "png": false,
      "raster": null,
      "svg": true
    }
  },
  "variants": {
    "stadium": {
      "idle": {
        "tier1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "construction": {
        "stage1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage4": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage5": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "aiVerified": true,
      "aiIdleVerified": true,
      "aiConstructionVerified": true,
      "rasterCount": 8,
      "requiredRaster": 8,
      "idleRasterCount": 3,
      "constructionRasterCount": 5
    },
    "academy": {
      "idle": {
        "tier1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "construction": {
        "stage1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage4": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage5": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "aiVerified": true,
      "aiIdleVerified": true,
      "aiConstructionVerified": true,
      "rasterCount": 8,
      "requiredRaster": 8,
      "idleRasterCount": 3,
      "constructionRasterCount": 5
    },
    "office": {
      "idle": {
        "tier1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "construction": {
        "stage1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage4": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage5": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "aiVerified": true,
      "aiIdleVerified": true,
      "aiConstructionVerified": true,
      "rasterCount": 8,
      "requiredRaster": 8,
      "idleRasterCount": 3,
      "constructionRasterCount": 5
    },
    "finance": {
      "idle": {
        "tier1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "construction": {
        "stage1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage4": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage5": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "aiVerified": true,
      "aiIdleVerified": true,
      "aiConstructionVerified": true,
      "rasterCount": 8,
      "requiredRaster": 8,
      "idleRasterCount": 3,
      "constructionRasterCount": 5
    },
    "medical": {
      "idle": {
        "tier1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "construction": {
        "stage1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage4": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage5": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "aiVerified": true,
      "aiIdleVerified": true,
      "aiConstructionVerified": true,
      "rasterCount": 8,
      "requiredRaster": 8,
      "idleRasterCount": 3,
      "constructionRasterCount": 5
    },
    "gym": {
      "idle": {
        "tier1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "tier3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "construction": {
        "stage1": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage2": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage3": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage4": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        },
        "stage5": {
          "webp": false,
          "png": true,
          "raster": "png",
          "svg": true
        }
      },
      "aiVerified": true,
      "aiIdleVerified": true,
      "aiConstructionVerified": true,
      "rasterCount": 8,
      "requiredRaster": 8,
      "idleRasterCount": 3,
      "constructionRasterCount": 5
    }
  }
} as const;

export const AI_VERIFIED_CAMPUS_VARIANTS = ["stadium","academy","office","finance","medical","gym"] as CampusBuildingVariant[];

export const AI_IDLE_VERIFIED_CAMPUS_VARIANTS = ["stadium","academy","office","finance","medical","gym"] as CampusBuildingVariant[];

export const HAS_AI_MASTER_BACKGROUND = true;
